import {
    MyPortfolio, FrontsideBlog, FyloLandingPage,
    TasksApp, PequenosTalentos, SmartToys,
    MyCalculator, BootstrapCV, RepoFinder, BeHealthy,
    TabNews
} from '../assets/imgs';

export const projects = [
    {
        img: BeHealthy,
        name: "Behealthy",
        description: "Aplicação intuitiva para ver treinos e alimentação organizadamente.",
        repo: "https://github.com/edwardribas/behealthy",
        preview: "https://ribby-behealthy.netlify.app/",
        technologies: ['React', 'SCSS', 'PWA'],
    },
    {
        img: MyPortfolio,
        name: "Meu Portfólio",
        description: "O lugar pelo qual você pode ver e analisar alguns dos meus projetos.",
        repo: "https://github.com/edwardribas/portfolio",
        preview: "ttps://edwardribas.netlify.app/",
        technologies: ['React', 'SCSS', 'PWA'],
    },
    {
        img: TabNews,
        name: "TabNews",
        description: "Reconceito de um fórum open-source feito pela comunidade para a comunidade.",
        repo: "https://github.com/edwardribas/tabnews-redesign",
        preview: "https://tabnews-redesign.vercel.app",
        technologies: ['NextJS 13', 'SCSS'],
    },
    {
        img: FrontsideBlog,
        name: "Frontside",
        description: "Um portal de artigos com o intuito de facilitar o entendimento de assuntos sobre web.",
        repo: "https://github.com/edwardribas/frontside",
        preview: "https://frontsideclub.netlify.app/",
        technologies: ['HTML', 'CSS', 'JavaScript'],
    },
    {
        img: FyloLandingPage,
        name: "Fylo",
        description: "Desafio do Frontend Mentor que consiste na construção de uma landing page.",
        repo: "https://github.com/edwardribas/fylo-landing-page",
        preview: "https://ribas-fylopage.netlify.app/",
        technologies: ['React', 'SCSS'],
    },
    {
        img: TasksApp,
        name: "Tarefas",
        description: "Aplicação simples de tarefas que armazena no localStorage por meio de JSON stringify.",
        repo: "https://github.com/edwardribas/js-practice/tree/main/12%20-%20Tarefas",
        preview: "https://gitribas-tasks.netlify.app/",
        technologies: ['HTML', 'CSS', 'JavaScript'],
    },
    {
        img: PequenosTalentos,
        name: "Pequenos Talentos",
        description: "Landing page feita para o projeto Pequenos Talentos da Tecnologia Única.",
        repo: "https://github.com/edwardribas/smalltalents",
        preview: "https://pequenostalentos.tecnologiaunica.com.br/",
        technologies: ['React', 'CSS'],
    },
    {
        img: SmartToys,
        name: "SmartToys",
        description: "Uma das primeiras landing pages que eu fiz, feita para um projeto institucional.",
        repo: "https://github.com/edwardribas/smart-toys",
        preview: "https://edwardribas.github.io/smart-toys",
        technologies: ['HTML', 'CSS', 'JavaScript'],
    },
    {
        img: BootstrapCV,
        name: "Bootstrap CV",
        description: "Avaliação institucional, se trata de um portfólio simples feito utilizando o Bootstrap",
        repo: "https://github.com/edwardribas/smart-toys",
        preview: "https://edwardribas.github.io/smart-toys",
        technologies: ['HTML', 'CSS', 'Bootstrap'],
    },
    {
        img: MyCalculator,
        name: "Calculadora",
        description: "Calculadora simples feita para praticar JavaScript.",
        repo: "https://github.com/edwardribas/calculator",
        preview: "https://edwardribas.github.io/calculator/",
        technologies: ['HTML', 'CSS', 'Bootstrap', 'JavaScript'],
    },
    {
        img: RepoFinder,
        name: "Repo Finder",
        description: "Aplicação assíncrona que consome a API do Github para retornar dados de usuários.",
        repo: "https://github.com/edwardribas/repo-finder",
        preview: "https://edwardribas.github.io/repo-finder/",
        technologies: ['HTML', 'CSS','JavaScript'],
    },
];